### ISSUE TITLE
Bot fails when "Require pull request reviews before merging" is selected

### ISSUE THREAD

**Issue by ttimbers** [benjefferies/branch-protection-bot#6]
This bot is a great idea! I have been using it and it generally works well, however, when I add the rule "Require pull request reviews before merging" for master branch protection then I get an error that At least 1 approving review is required by reviewers with write access (pasted below, but for context you can see the logs [here](https://github.com/ttimbers/convertempPy/runs/504949243?check_suite_focus=true))

```
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access. 
```

Would it be possible to modify the bot such that this rule is set to false as well when we disable master branch protection? I guess it would be possible, looking at the docs I see that `required_pull_request_reviews` can be set to `NULL` to do so using the branch protection API? The `github3` docs [here](https://github3py.readthedocs.io/en/master/api-reference/repos.html#github3.repos.branch.ProtectionRequiredPullRequestReviews) also suggest it could be done with `github3.repos.branch.ProtectionRequiredPullRequestReviews`?

**Comment by benjefferies** [comment]
Thanks, @ttimbers. I've manually tested this scenario; enable "Require pull request reviews before merging, then disable "Include administrators"). Here's what I see in my logs for the before and after

```
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 1.21 KiB | 310.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
To github.com:benjefferies/branch-protection-bot.git
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'git@github.com:benjefferies/branch-protection-bot.git'
(⎈ ➜  branch-protection-bot git:(master) ✗ git push origin master
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (5/5), 1.21 KiB | 414.00 KiB/s, done.
Total 5 (delta 2), reused 0 (delta 0)
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:benjefferies/branch-protection-bot.git
   3c75a13..672be81  master -> master
```

Are you explicitly disabling "Include administrators" in your CI? 

```
    - name: Force disable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        enforce_admins: false
    - name: Force enable "include administrators" branch protection
      uses: benjefferies/branch-protection-bot@master
      if: always()
      with:
        access-token: ${{ secrets.ACCESS_TOKEN }}
        enforce_admins: true
```

If you use the toggle method and your CI fails before switching it back on you can get out of sync.

Hope this information help
